### PR TITLE
Increase max-width for TODO

### PR DESCRIPTION
**Pull request by w3bdesign**
fix: Fixed width for TODO listings on desktop view.

### CODE REVIEW

**Comment by leonardopliski** [comment]
Hey @w3bdesign!

Thanks for your contribution! May you update the commit to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention?

**Comment by w3bdesign** [comment]
> 
> 
> Hey @w3bdesign!
> 
> Thanks for your contribution! May you update the commit to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention?

Sorry, I haven't heard of conventionalcommits before.

Is it ok now, and if not, can you modify it so that it is correct?

**Comment by leonardopliski** [comment]
It's almost there,

Things to be improved:

1. The first line of your commit message must have a maximum of 50 characters long. No more, and (ideally), no less. See [50/72 rule](https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c).
2. It's not a `feat` type commit, this change is related to the `style` context, and isn't a new feature. See [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
3. It's recommended to break your commits on multiple lines. See [How can I make git commit messages divide into multiple lines](https://stackoverflow.com/questions/29933349/how-can-i-make-git-commit-messages-divide-into-multiple-lines/42078093)

So the desired message should look like:
```
style(todo-listings): increased width on desktop

* It didn't look good on desktop screens.
```

**Comment by w3bdesign** [comment]
I deleted the old repository for this, so I can't amend the changes.

I created a new PR for it instead.

**Pull request closed without merging**
