### PR TITLE
feat: wait on server

### PR DESCRIPTION
**Pull request by flaurida**
Cool project!

I'm trying to fix your tests :) When I ran the server locally it took a bit of time to start up, so added wait on with a 2 minute timeout. Let's see if this works?

### CODE REVIEW

**Comment by flaurida** [comment]
Update - I tried even a timeout of 10 minutes and the server did not start in that time frame. In other words, the test URL (`http://localhost:3000/react-antd-todo`) is not available, so the tests cannot run.

 I noticed it took quite a bit of time for me locally, so wonder if that could be the issue?

**Comment by leonardopliski** [comment]
Hey @flaurida, 

Glad to see you here! Thanks for contributing to the project,

What do you think about generating the build normally (with `yarn build`) and then use a package like [serve](https://www.npmjs.com/package/serve) to serve the final build and run the tests reusing the build step?

**Comment by flaurida** [comment]
That might work! I'll take a look tomorrow :)

**Comment by flaurida** [comment]
Fixed on a different branch #4 - closing this one, please check the other one!

**Pull request closed without merging**
